"""Models package."""

from models.database import (
    ArtworkCache,
    Config,
    EditionBackup,
    EditionConfig,
    Issue,
    Scan,
    ScanEvent,
    Schedule,
    Suggestion,
)
from models.schemas import (
    ArtworkType,
    HealthResponse,
    IssueListResponse,
    IssueResponse,
    IssueStatus,
    IssueType,
    MediaType,
    PlexConnectRequest,
    PlexConnectResponse,
    PlexLibrariesResponse,
    PlexLibrary,
    Provider,
    ScanConfig,
    ScanProgressEvent,
    ScanStartRequest,
    ScanStatus,
    ScanStatusResponse,
    ScanType,
    ScheduleCreateRequest,
    ScheduleListResponse,
    ScheduleResponse,
    SuggestionResponse,
)

__all__ = [
    # Database models
    "ArtworkCache",
    "Config",
    "EditionBackup",
    "EditionConfig",
    "Issue",
    "Scan",
    "ScanEvent",
    "Schedule",
    "Suggestion",
    # Schemas
    "ArtworkType",
    "HealthResponse",
    "IssueListResponse",
    "IssueResponse",
    "IssueStatus",
    "IssueType",
    "MediaType",
    "PlexConnectRequest",
    "PlexConnectResponse",
    "PlexLibrariesResponse",
    "PlexLibrary",
    "Provider",
    "ScanConfig",
    "ScanProgressEvent",
    "ScanStartRequest",
    "ScanStatus",
    "ScanStatusResponse",
    "ScanType",
    "ScheduleCreateRequest",
    "ScheduleListResponse",
    "ScheduleResponse",
    "SuggestionResponse",
]
